version: "2"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - lll
    - varnamelen
    - noinlineerr
    - err113
    - funlen
    - tagliatelle
    - wsl  # Deprecated replaced by wsl_v5
    - testpackage
    - gomodguard # Deprecated replaced by gomodguard_v2
    - gomodguard_v2
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
